version: "3.3"

services:
  nginx-proxy:
    container_name: ${NGINX_WEB_SEVICE_NAME}
    build:
      context: .
      dockerfile: setup-dockerfile/nginx.Dockerfile
    ports:
      - ${IPv4}:${HTTP_PORT}:80
      - ${IPv4}:${HTTPS_PORT}:443
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${LE_FILES_PATH}/etc/letsencrypt:/etc/letsencrypt:ro
      - ${ACME_FILES_PATH}/tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - proxied
    restart: always

services:
  letsencrypt:
    container_name: 'certbot-service'
    image: certbot/certbot:v1.17.0
    

  certbot:
    image: certbot/certbot
    container_name: ${CERTBOT_SERVICE_NAME}
    depends_on:
      - nginx-proxy
    volumes:
      # Store generated certificates
      - ${LE_FILES_PATH}/etc/letsencrypt:/etc/letsencrypt
      - ${ACME_FILES_PATH}/tmp/acme_challenge:/tmp/acme_challenge
      - ${ACME_FILES_PATH}/www/.well-known:/var/www/.well-known
      - ${LE_FILES_PATH}/ssl:/etc/letsencrypt
      - ${LE_FILES_PATH}/ssl-log:/var/log/letsencrypt
    profiles:
      - certbot
    command: sh -c "certbot certonly --webroot -w /tmp/acme_challenge -d sillyroach.com --text --agree-tos --email silly.cockroach@protonmail.com --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    environment:
      - TERM=xterm
    
networks:
  proxied:
    driver: bridge